version: '3.8'
services:
  next-pr:
    container_name: next-pr
    build:
      context: push-up-rivals
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./push-up-rivals:/app
    networks:
      - proxy_network
  
  postgresql-pr:
    container_name: db-pr
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata-pr:/var/lib/postgresql/data
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true

volumes:
  pgdata-pr: